import React, { useState } from 'react';
import { BusinessCanvasState, CanvasSection } from '../types';
import { CanvasCard } from './CanvasCard';
import { SECTION_LABELS } from '../constants';
import { ClipboardCopy, FileText, Check } from 'lucide-react';

interface BusinessCanvasProps {
  canvasState: BusinessCanvasState;
  onCardClick: (section: CanvasSection) => void;
}

export const BusinessCanvas: React.FC<BusinessCanvasProps> = ({ canvasState, onCardClick }) => {
  const [copied, setCopied] = useState(false);

  const handleCopyReport = () => {
    let report = `# Business Model Canvas Report\nGenerated by BizArchitect AI\n\n`;
    Object.entries(canvasState).forEach(([key, item]) => {
      const label = SECTION_LABELS[key] || key;
      report += `## ${label} (${item.status.toUpperCase()})\n${item.content || '(Empty)'}\n\n*Analyst Note: ${item.reasoning}*\n\n---\n\n`;
    });
    
    navigator.clipboard.writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="h-full w-full flex flex-col bg-slate-950">
      {/* Toolbar */}
      <div className="h-14 border-b border-slate-800 bg-slate-900/50 px-6 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-2">
          <div className="w-1.5 h-6 bg-indigo-500 rounded-full"></div>
          <h2 className="text-sm font-semibold text-slate-200 tracking-wide">Strategic Overview</h2>
        </div>
        <button 
          onClick={handleCopyReport}
          className="flex items-center gap-2 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium rounded-md border border-slate-700 transition-all"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <ClipboardCopy className="w-3.5 h-3.5" />}
          {copied ? 'Report Copied' : 'Export Report'}
        </button>
      </div>

      {/* Grid Canvas */}
      <div className="flex-1 p-4 overflow-y-auto">
        <div className="h-full grid grid-cols-1 md:grid-cols-5 md:grid-rows-3 gap-4 min-h-[700px] max-w-[1600px] mx-auto">
          {/* Left Column: Key Partners (Tall) */}
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.KeyPartners]} 
            item={canvasState.keyPartners}
            gridArea="1 / 1 / span 2 / span 1"
            onClick={() => onCardClick(CanvasSection.KeyPartners)}
          />

          {/* Left-Middle Stack: Activities & Resources */}
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.KeyActivities]} 
            item={canvasState.keyActivities}
            gridArea="1 / 2 / span 1 / span 1"
            onClick={() => onCardClick(CanvasSection.KeyActivities)}
          />
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.KeyResources]} 
            item={canvasState.keyResources}
            gridArea="2 / 2 / span 1 / span 1"
            onClick={() => onCardClick(CanvasSection.KeyResources)}
          />

          {/* Center: Value Prop (Tall) */}
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.ValueProposition]} 
            item={canvasState.valueProposition}
            gridArea="1 / 3 / span 2 / span 1"
            onClick={() => onCardClick(CanvasSection.ValueProposition)}
          />

          {/* Right-Middle Stack: Relationships & Channels */}
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.CustomerRelationships]} 
            item={canvasState.customerRelationships}
            gridArea="1 / 4 / span 1 / span 1"
            onClick={() => onCardClick(CanvasSection.CustomerRelationships)}
          />
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.Channels]} 
            item={canvasState.channels}
            gridArea="2 / 4 / span 1 / span 1"
            onClick={() => onCardClick(CanvasSection.Channels)}
          />

          {/* Right Column: Customer Segments (Tall) */}
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.CustomerSegments]} 
            item={canvasState.customerSegments}
            gridArea="1 / 5 / span 2 / span 1"
            onClick={() => onCardClick(CanvasSection.CustomerSegments)}
          />

          {/* Bottom Row: Cost & Revenue */}
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.CostStructure]} 
            item={canvasState.costStructure}
            gridArea="3 / 1 / span 1 / span 2.5" // Span half bottom
            onClick={() => onCardClick(CanvasSection.CostStructure)}
          />
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.RevenueStreams]} 
            item={canvasState.revenueStreams}
            gridArea="3 / 3.5 / span 1 / span 2.5" // Span half bottom
            onClick={() => onCardClick(CanvasSection.RevenueStreams)}
          />
        </div>
      </div>
    </div>
  );
};