import React, { useState } from 'react';
import { BusinessCanvasState, CanvasSection, CanvasItem } from '../types';
import { CanvasCard } from './CanvasCard';
import { SECTION_LABELS } from '../constants';
import { ClipboardCopy, FileText, Check, ChevronDown, Download, FileJson, FileType } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { Document, Packer, Paragraph, HeadingLevel, TextRun } from 'docx';

interface BusinessCanvasProps {
  canvasState: BusinessCanvasState;
  onCardClick: (section: CanvasSection) => void;
}

export const BusinessCanvas: React.FC<BusinessCanvasProps> = ({ canvasState, onCardClick }) => {
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [copyFeedback, setCopyFeedback] = useState(false);

  const generateReportContent = () => {
    let report = `# Business Model Canvas Report\nGenerated by BizArchitect AI\n\n`;
    Object.entries(canvasState).forEach(([key, val]) => {
      const item = val as CanvasItem;
      const label = SECTION_LABELS[key] || key;
      report += `## ${label} (${item.status.toUpperCase()})\n${item.content || '(Empty)'}\n\n*Analyst Note: ${item.reasoning}*\n\n---\n\n`;
    });
    return report;
  };

  const handleExportMarkdown = () => {
    const report = generateReportContent();
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'BizArchitect_Report.md';
    a.click();
    setShowExportMenu(false);
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text("Business Model Canvas Report", 10, 10);
    doc.setFontSize(10);
    doc.text("Generated by BizArchitect AI", 10, 16);
    
    let y = 30;
    Object.entries(canvasState).forEach(([key, val]) => {
      const item = val as CanvasItem;
      const label = SECTION_LABELS[key] || key;
      
      if (y > 250) {
        doc.addPage();
        y = 20;
      }

      doc.setFont("helvetica", "bold");
      doc.setTextColor(50, 50, 50);
      doc.text(`${label} (${item.status.toUpperCase()})`, 10, y);
      y += 6;

      doc.setFont("helvetica", "normal");
      doc.setTextColor(0, 0, 0);
      const lines = doc.splitTextToSize(item.content || "(Empty)", 180);
      doc.text(lines, 10, y);
      y += (lines.length * 5) + 4;

      doc.setFont("helvetica", "italic");
      doc.setTextColor(100, 100, 100);
      const noteLines = doc.splitTextToSize(`Analyst Note: ${item.reasoning}`, 180);
      doc.text(noteLines, 10, y);
      y += (noteLines.length * 5) + 10;
    });

    doc.save("BizArchitect_Report.pdf");
    setShowExportMenu(false);
  };

  const handleExportWord = () => {
    const sections = Object.entries(canvasState).map(([key, val]) => {
      const item = val as CanvasItem;
      const label = SECTION_LABELS[key] || key;
      return [
        new Paragraph({
          text: `${label} (${item.status.toUpperCase()})`,
          heading: HeadingLevel.HEADING_2,
        }),
        new Paragraph({
          text: item.content || "(Empty)",
          spacing: { after: 100 },
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: `Analyst Note: ${item.reasoning}`,
              italics: true,
              color: "666666"
            })
          ],
          spacing: { after: 300 },
        })
      ];
    }).flat();

    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            text: "Business Model Canvas Report",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({
            text: "Generated by BizArchitect AI",
            spacing: { after: 400 },
          }),
          ...sections
        ],
      }],
    });

    Packer.toBlob(doc).then((blob) => {
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'BizArchitect_Report.docx';
      a.click();
    });
    setShowExportMenu(false);
  };

  const handleCopyClipboard = () => {
    navigator.clipboard.writeText(generateReportContent());
    setCopyFeedback(true);
    setTimeout(() => setCopyFeedback(false), 2000);
    setShowExportMenu(false);
  };

  return (
    <div className="h-full w-full flex flex-col bg-slate-50 dark:bg-slate-950 transition-colors">
      {/* Toolbar */}
      <div className="h-14 border-b border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900/50 px-6 flex items-center justify-between shrink-0 transition-colors">
        <div className="flex items-center gap-2">
          <div className="w-1.5 h-6 bg-indigo-600 rounded-full"></div>
          <h2 className="text-sm font-semibold text-slate-800 dark:text-slate-200 tracking-wide">Strategic Overview</h2>
        </div>
        
        <div className="relative">
          <button 
            onClick={() => setShowExportMenu(!showExportMenu)}
            className="flex items-center gap-2 px-3 py-1.5 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 text-xs font-medium rounded-md border border-slate-200 dark:border-slate-700 transition-all shadow-sm"
          >
            <Download className="w-3.5 h-3.5" />
            Export
            <ChevronDown className="w-3 h-3 opacity-70" />
          </button>

          {showExportMenu && (
            <>
              <div className="fixed inset-0 z-10" onClick={() => setShowExportMenu(false)} />
              <div className="absolute top-full right-0 mt-2 w-48 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg shadow-xl z-20 py-1 overflow-hidden animate-in fade-in zoom-in-95 duration-100">
                <button onClick={handleExportPDF} className="w-full flex items-center gap-3 px-3 py-2 text-left text-xs text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700">
                  <FileType className="w-4 h-4 text-rose-500" />
                  Export as PDF
                </button>
                <button onClick={handleExportWord} className="w-full flex items-center gap-3 px-3 py-2 text-left text-xs text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700">
                  <FileText className="w-4 h-4 text-blue-500" />
                  Export as Word
                </button>
                <button onClick={handleExportMarkdown} className="w-full flex items-center gap-3 px-3 py-2 text-left text-xs text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700">
                  <FileJson className="w-4 h-4 text-slate-500" />
                  Export as Markdown
                </button>
                <div className="h-px bg-slate-200 dark:bg-slate-700 my-1"></div>
                <button onClick={handleCopyClipboard} className="w-full flex items-center gap-3 px-3 py-2 text-left text-xs text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700">
                  {copyFeedback ? <Check className="w-4 h-4 text-emerald-500" /> : <ClipboardCopy className="w-4 h-4 text-indigo-500" />}
                  {copyFeedback ? 'Copied!' : 'Copy to Clipboard'}
                </button>
              </div>
            </>
          )}
        </div>
      </div>

      {/* Grid Canvas */}
      <div className="flex-1 p-4 overflow-y-auto">
        <div className="h-full grid grid-cols-1 md:grid-cols-5 md:grid-rows-3 gap-4 min-h-[700px] max-w-[1600px] mx-auto">
          {/* Left Column: Key Partners (Tall) */}
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.KeyPartners]} 
            item={canvasState.keyPartners}
            gridArea="1 / 1 / span 2 / span 1"
            onClick={() => onCardClick(CanvasSection.KeyPartners)}
          />

          {/* Left-Middle Stack: Activities & Resources */}
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.KeyActivities]} 
            item={canvasState.keyActivities}
            gridArea="1 / 2 / span 1 / span 1"
            onClick={() => onCardClick(CanvasSection.KeyActivities)}
          />
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.KeyResources]} 
            item={canvasState.keyResources}
            gridArea="2 / 2 / span 1 / span 1"
            onClick={() => onCardClick(CanvasSection.KeyResources)}
          />

          {/* Center: Value Prop (Tall) */}
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.ValueProposition]} 
            item={canvasState.valueProposition}
            gridArea="1 / 3 / span 2 / span 1"
            onClick={() => onCardClick(CanvasSection.ValueProposition)}
          />

          {/* Right-Middle Stack: Relationships & Channels */}
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.CustomerRelationships]} 
            item={canvasState.customerRelationships}
            gridArea="1 / 4 / span 1 / span 1"
            onClick={() => onCardClick(CanvasSection.CustomerRelationships)}
          />
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.Channels]} 
            item={canvasState.channels}
            gridArea="2 / 4 / span 1 / span 1"
            onClick={() => onCardClick(CanvasSection.Channels)}
          />

          {/* Right Column: Customer Segments (Tall) */}
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.CustomerSegments]} 
            item={canvasState.customerSegments}
            gridArea="1 / 5 / span 2 / span 1"
            onClick={() => onCardClick(CanvasSection.CustomerSegments)}
          />

          {/* Bottom Row: Cost & Revenue */}
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.CostStructure]} 
            item={canvasState.costStructure}
            gridArea="3 / 1 / span 1 / span 2.5" // Span half bottom
            onClick={() => onCardClick(CanvasSection.CostStructure)}
          />
          <CanvasCard 
            title={SECTION_LABELS[CanvasSection.RevenueStreams]} 
            item={canvasState.revenueStreams}
            gridArea="3 / 3.5 / span 1 / span 2.5" // Span half bottom
            onClick={() => onCardClick(CanvasSection.RevenueStreams)}
          />
        </div>
      </div>
    </div>
  );
};